### ISSUE TITLE
FR: target="_blank" for links

### ISSUE THREAD

**Issue by JSoko** [janis91/nextnotes#18]
# Feature request
## Expected Behavior
Links hat target="_blank" set or it ist possible to set target="_bank" in the markdowm

## Current Behavior
[test](https://sokolowski.org)

follows to

`<a href="https://sokolowski.org">test</a>`

## Possible Solution
Create a markdown option for target="_blank" or give a option in settings to choose if links should be target="_blank" or not

## Advantage
especially in Notes, if I reffer to extern sites, I prever to have links opened in a new tab without pressing [Strg]

**Comment by janis91** [comment]
Good idea.

**Comment by janis91** [comment]
After looking into this, I came up with a simple solution:

````
[Google](https://google.de)
<a href="https://www.google.de" target="_blank">Google</a>
````

The markdown editor supports some (not all, but the most) html markup. If your note requires a special function which isn't supported by the standard markdown language, you could normally use the html markup to get the required result.
I think this is a good solution for this, because it's like in github or other known places where markdown is a used language.

**Comment by JSoko** [comment]
>  think this is a good solution for this,
Yes, it is , but should be mentioned in the markdown-help

```
**Links**

[Text to display](http://www.example.com)

For advanced features also html markup can be used . 
E.g.: `<a href="https://www.google.de" target="_blank">Google</a>`


```

**Comment by janis91** [comment]
Yeah you're right. I will add it to the markdown guide.

**Comment by janis91** [comment]
Forked the markdownguide and created a gh-pages version for the guide.
