### ISSUE TITLE
Project future

### ISSUE THREAD

**Issue by gsantner** [janis91/nextnotes#39]
Hi there,
I just wanted to know what this project is leading to.

I'm somewhat confused why there are so much notes apps out there, for just showing and editing notes/text-files. I found these notes apps for own/nextcloud:
* [nextnotes (this one)](https://github.com/janis91/nextnotes)
* [ownNote](https://apps.owncloud.com/content/show.php/ownNote+-+Notes+Application?content=168512)
* [NC notes](https://github.com/nextcloud/notes)
  * -> fork of [~~OC notes~~](https://github.com/owncloud/notes)

I just looked at the commits and saw the `nextcloud-bot` there. 

* So is this going to replace the `nextcloud/notes` app?  
* Is this going to be merged in the `nextcloud/notes` app?  
* If neither, why not work together on **one** solution for a notes app?

**Comment by janis91** [comment]
1. This is not going to replace the nextcloud/notes app. Once I thought about a fork of this app, but I wanted to create an app on my own, because I didn't do this before and I wanted to learn it.. So I started from zero.
2. As it isn't a fork and I didn't go by the notes project, I assume it would be very difficult to merge this...
3. I am completely with you, that it would be a big benefit for the note app, if there would be some more people working together!

But: One thing I aim at, with my solution, is to provide a notes app for collaborating and publishing to external parties too.. 

The last thing I want to mention is, that I had a bit too much work in the last couple of weeks, so that the progress of this project stopped. Next week I will have my masters degree finished - "YES!" - and after that I guess I will have more time to come back to and put some effort in this.

I think a solution that we can work together sounds good for me, if we can get together with my way of thinking, what a notes app could provide in the area of a cloud.

**Comment by phsc** [comment]
I really like your Nextnotes app. It is way slimmer than the original Notes app (~1.5 MB vs. ~6 MB) and it has some cool features (SimpleMDE, Tags, Search). And it will be even better as soon as you will support to store the notes on the filesystem.
I even think, that your Notes app should become the new default notes app for Nextcloud. Not that I want to dishonor the work on the current default notes app, but your app really has a lot potential!

**Comment by putt1ck** [comment]
See my (completely OT) response to the thread on https://github.com/nextcloud/notes/issues/7

**Comment by JSoko** [comment]
@janis91 I know you're very engaged in OCR at the moment and I hope you've done your master thesis with great success.
But please let me ask if there will be further developement of nextnotes...
...I wait impatiently for an improved version ;-)

**Comment by janis91** [comment]
@JSoko Thank you for your wishes :) At the moment I am waiting for an answer to this issue: https://github.com/nextcloud/notes/issues/37

I don't know if it is worth the effort to split development into nextnotes and nextcloud/notes and would appreciate it to go for nextcloud/notes if the main devs go with me and my opinion for a future notes app and its features.

I can absolutely understand the impatience and hope for a little progress in the next days, but I cannot guarantee it.

**Comment by JSoko** [comment]
@janis91 Thank you for your reply.

I'll be patient and wait for a great app ;-)

**Comment by janis91** [comment]
Hi there. Sorry for the delay. I had much to do and it seems not getting lesser. I will have a look into the official notes app, as soon as possible and will try to get some more drive to the features which have to be included in a notes app following my opinion.

For now I will stop the development of nextnotes and will see if it's going well to work together on one notes app.

Only if this is not successful, I will perhaps get back to nextnotes.
